### TASK A

In [21]:
# user_mame = input("Username")
# user_password = input("Password")

In [22]:
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from tqdm import tqdm
import pandas as pd
import os
import numpy as np
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import datetime
import string
from nltk import FreqDist
import spacy
import openai
from openai.error import ServiceUnavailableError, APIError, Timeout
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

current_path = os.getcwd()
current_path = current_path.split('Beer_Recommendation_Engine')
path = current_path[0] + 'Beer_Recommendation_Engine'
path

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

In [23]:
# current_path = os.getcwd()
# current_path = current_path.split('Beer_Recommendation_Engine')
# path = current_path[0] + 'Beer_Recommendation_Engine'
# path

In [24]:
# def login():
#     wd = webdriver.Chrome(options=chrome_options)

#     url = 'https://www.beeradvocate.com/community/login/'

#     wd.get(url)
#     username = WebDriverWait(wd, 20).until(
#                     EC.element_to_be_clickable(
#                         wd.find_element(by=By.XPATH, value='/html/body/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/form/dl[1]/dd/input')))
#     username.send_keys(user_mame)

#     password = WebDriverWait(wd, 20).until(
#                     EC.element_to_be_clickable(
#                         wd.find_element(by=By.XPATH, value='/html/body/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/form/dl[2]/dd/ul/li[3]/input')))
#     password.send_keys(user_password)

#     remeber_password = WebDriverWait(wd, 20).until(
#                     EC.element_to_be_clickable(
#                         wd.find_element(by=By.XPATH, value='/html/body/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/form/dl[3]/dd/label/input')))
#     remeber_password.click()

#     login = WebDriverWait(wd, 20).until(
#                     EC.element_to_be_clickable(
#                         wd.find_element(by=By.XPATH, value='/html/body/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/form/dl[3]/dd/input')))
#     login.click()

#     return wd

In [25]:
# wd = webdriver.Chrome(options=chrome_options)

# wd = login()

# url = 'https://www.beeradvocate.com/beer/top-rated/'

# wd.get(url)

# table = wd.find_element(by=By.TAG_NAME, value='table')
# brands = table.find_elements(by=By.TAG_NAME, value='a')

# beer_brand_sites = []
# i = 1
# for brand in tqdm(brands):
#     brand_url = brand.get_attribute('href')
#     name = brand.text
#     len_url = len(brand_url.split('/'))
#     if len_url == 8:
#         beer_brand_sites.append([name, brand_url, i])
#         i += 1

# beer_brand_sites = pd.DataFrame(beer_brand_sites, columns=['beer_name', 'url', 'pos'])
# beer_brand_sites

In [26]:
# pos = 140
# for url in (pbar := tqdm(beer_brand_sites['url'][pos:])):
#     scraped_data = []
#     url = url + '?view=beer&show=recent&start=' + str(0) + '#lists'
#     wd.get(url)
#     links = wd.find_elements(by=By.TAG_NAME, value='a')

#     l = []
#     for link in links:
#         url = link.get_attribute('href')
#         if url != None:
#             if 'recent&start' in url:
#                 url = url.split('?view=beer&show=recent&start=')[-1]
#                 last = url.split('#')[0]
#                 l.append(int(last))
#     l = max(l)
    
#     i = 1
#     url = beer_brand_sites['url'][pos]
#     while i<=l:
#         if i == 1:
#             i = 0
#             beer_url = url + '?view=beer&show=recent&start=' + str(i) + '#lists'
#             i = 20
#         else:
#             beer_url = url + '?view=beer&show=recent&start=' + str(i) + '#lists'
#             i += 20
            
#         pbar.set_description(f"Fetching data from {beer_url}")

#         wd.get(beer_url)

#         comms = wd.find_elements(by=By.ID, value='rating_fullview_container')

#         for comm in comms:
#             row = [beer_brand_sites['pos'][pos], beer_brand_sites['beer_name'][pos]]
#             data = comm.find_element(by=By.ID, value='rating_fullview_content_2')
#             data = data.text
#             data = data.split('\n')
#             # print(data)
#             if len(data) == 3:
#                 rating = data[0].split('Rated: ')
#                 rating = rating[1].split(' ')
#                 rating = float(rating[0])
#                 row.append(rating)
                
#                 for j in range(5):
#                     row.append(np.nan)

#                 user = data[0].split('by ')
#                 user = user[1].split(' ')
#                 user = str(user[0])
#                 row.append(user)

#                 place = data[0].split('from ')
#                 place = str(place[-1])
#                 row.append(place)

#                 row.append(None)

#                 date = data[-1].split(' ')
#                 if str(date[-1]) == 'Report':
#                     date = " ".join(date[0:-1])
#                     date = date.strip()
#                 else:
#                     date = data[-1]    
#                 row.append(date)
#             elif str(data[3])[:4] == 'look':
#                 rating = data[2].split('/')
#                 rating = float(rating[0])
#                 row.append(rating)

#                 attributes = data[3].split('|')
#                 for attribute in attributes:
#                     attribute = attribute.strip()
#                     attribute = float(attribute.split(' ')[1])
#                     row.append(attribute)

#                 user = data[0].split('by ')
#                 user = user[1].split(' ')
#                 user = str(user[0])
#                 row.append(user)

#                 place = data[0].split('from ')
#                 place = str(place[-1])
#                 row.append(place)

#                 comment = " ".join(data[4:-1])
#                 comment = comment.strip()
#                 row.append(comment)

#                 date = data[-1].split(' ')
#                 if str(date[-1]) == 'Report':
#                     date = " ".join(date[0:-1])
#                     date = date.strip()
#                 else:
#                     date = data[-1]    
#                 row.append(date)
#             else:
#                 rating = data[2].split('/')
#                 rating = float(rating[0])
#                 row.append(rating)

#                 for j in range(5):
#                     row.append(np.nan)

#                 user = data[0].split('by ')
#                 user = user[1].split(' ')
#                 user = str(user[0])
#                 row.append(user)

#                 place = data[0].split('from ')
#                 place = str(place[-1])
#                 row.append(place)

#                 comment = " ".join(data[3:-1])
#                 comment = comment.strip()
#                 row.append(comment)

#                 date = data[-1].split(' ')
#                 if str(date[-1]) == 'Report':
#                     date = " ".join(date[0:-1])
#                     date = date.strip()
#                 else:
#                     date = data[-1]    
#                 row.append(date)
#             scraped_data.append(row)
    
#     scraped_data = pd.DataFrame(scraped_data, columns=['pos', 'beer_name', 'final_rating', 'looks', 'smell', 'taste', 'feel', 'overall', 'user', 
#                                                    'place', 'comment', 'date'])
#     if pos==0:
#         scraped_data.to_csv(path + '/Data/beer_reviews.csv', mode='a', index=False, header=True)
#     else:
#         scraped_data.to_csv(path + '/Data/beer_reviews.csv', mode='a', index=False, header=False)
#     pos += 1

# wd.quit()

In [27]:
# scraped_data = pd.read_csv(path + '/Data/beer_reviews.csv')
# scraped_data

### Task B

In [28]:
beer_reviews = pd.read_csv(path + '/Data/beer_reviews.csv')
beer_reviews = beer_reviews.drop_duplicates()

def process_date(data):
    from datetime import date

    o_date = str(data)
    o_date = o_date.split(' ')
    if o_date[1] == 'at':
        return date.today()
    else:
        return data


beer_reviews = beer_reviews.loc[~beer_reviews['comment'].isnull()]
beer_reviews['date'] = beer_reviews['date'].apply(lambda row: process_date(row))
beer_reviews['date'] = pd.to_datetime(beer_reviews['date'])
beer_reviews = beer_reviews.loc[beer_reviews['date'] >= datetime.datetime(year=2019, month=1, day=1)]
beer_reviews = beer_reviews.reset_index(drop=True)
beer_reviews = beer_reviews.drop_duplicates('comment')
beer_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11893 entries, 0 to 11963
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   pos           11893 non-null  int64
 1   beer_name     11893 non-null  object
 2   final_rating  11893 non-null  float64
 3   looks         11893 non-null  float64
 4   smell         11893 non-null  float64
 5   taste         11893 non-null  float64
 6   feel          11893 non-null  float64
 7   overall       11893 non-null  float64
 8   user          11893 non-null  object
 9   place         11893 non-null  object
 10  comment       11893 non-null  object
 11  date          11893 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(1), object(4)
memory usage: 1.2+ MB

In [29]:
def generate_corpus(column, include_stopwords=True, stop_words=[]):
    corpus = " "
    if include_stopwords:
        for text in column:
            text = str(text)
            for i in list(string.punctuation):
                text = text.replace(i, ' ')
            
            text = text.lower()
            corpus += text
        
        corpus = corpus.split()
    else:
        for text in column:
            text = str(text)
            for i in list(string.punctuation):
                text = text.replace(i, ' ')
            
            text = text.lower()
            corpus += text
        
        corpus = corpus.split()

        corpus_filtered = []
        stop_words = set(stop_words)
        for word in corpus:
            if word not in stop_words:
                corpus_filtered.append(word)
        
        corpus = corpus_filtered
    
    return corpus

In [30]:
en = spacy.load("en_core_web_sm")
stop_words = en.Defaults.stop_words
corpus = generate_corpus(beer_reviews['comment'], include_stopwords=False, stop_words=stop_words)

word_freq = FreqDist()
for word in tqdm(corpus):
    word_freq[word] += 1

freq_dist = []
for rank, word in enumerate(word_freq):
    freq_dist.append([rank+1, word, word_freq[word]])

freq_dist = pd.DataFrame(freq_dist, columns=['Rank', 'Word', 'Count'])
freq_dist.to_csv(path + '/Support Files/Freq_Dist_new_comments.csv', index=False)
freq_dist

100%|██████████| 607954/607954 [00:00<00:00, 2933971.41it/s]

        Rank       Word  Count
0          1       beer   8692
1          2       head   6471
2          3          s   6144
3          4      taste   5652
4          5  chocolate   4784
...      ...        ...    ...
22509  22510        to”      1
22510  22511     extend      1
22511  22512   canister      1
22512  22513     8000th      1
22513  22514      14819      1

[22514 rows x 3 columns]

In [31]:
def process_column(column):
    data = list(column)
    for i in range(len(data)):
        text = str(data[i])
        for punct in list(string.punctuation):
             text = text.replace(punct, ' ')
        text = text.lower()
        data[i] = text
    return data

def replace_car_brands(data, map):
    for i in range(len(data)):
        text = data[i]
        l_text = text.split()
        for word in l_text:
            if word in map.keys():
                text = text.replace(word, map[word])
        data[i] = text.split()
    return data

In [32]:
comments = process_column(beer_reviews['comment'])

beer_attribute_map = pd.read_csv(path + '/Support FIles/Beeer_attributes.csv')

beer_attribute_dict = {}
for brand, model in zip(beer_attribute_map['Attribute'], beer_attribute_map['Variance']):
    beer_attribute_dict[model] = brand

comments = replace_car_brands(comments, beer_attribute_dict)

atribute_freq = []
for attribute in set(beer_attribute_dict.values()):
    try:
        atribute_freq.append([attribute, word_freq[attribute]])
    except:
        atribute_freq.append([attribute, 0])

atribute_freq = pd.DataFrame(atribute_freq, columns=['attribute', 'count'])
atribute_freq = atribute_freq.sort_values('count', ascending=False)
atribute_freq

      attribute  count
3          dark   4347
29        sweet   4075
4        coffee   3952
28       citrus   3059
22      vanilla   2952
16     balanced   1500
21      complex    984
8      cinnamon    908
7        fruity    843
27        hoppy    749
19    tangerine    735
5          tart    664
11        cocoa    600
9         melon    591
13      vintage    582
25       cherry    515
2         malty    484
10      apricot    471
23       herbal    464
1         crisp    462
15       papaya    448
12        spicy    402
26        honey    393
0         silky    360
18   aggressive    184
6        robust    155
14    chocolaty     32
24     diacetyl     24
17       estery     16
20  roast/toast      0

### Task C

In [33]:
attributes = list(set(beer_attribute_dict.values()))

def tf(text, attribute, map):
    text = str(text)
    text = text.strip()
    
    for punct in list(string.punctuation):
        text = text.replace(punct, ' ')
    text = text.lower()
    
    l_text = text.split()
    for word in l_text:
        if word in map.keys():
            text = text.replace(word, map[word])
    
    text = text.split()
    
    count = 0
    for t_word in text:
        if t_word==attribute:
            count += 1
    
    return count

for attribute in (pbar := tqdm(attributes)):
    pbar.set_description(f"Calculating TFs for {attribute}")
    beer_reviews[attribute] = beer_reviews['comment'].apply(lambda row: tf(row, attribute, beer_attribute_dict))
beer_reviews

Calculating TFs for sweet: 100%|██████████| 30/30 [00:06<00:00,  4.75it/s]

,pos,beer_name,final_rating,looks,smell,taste,feel,overall,user,place,...,roast/toast,complex,vanilla,herbal,diacetyl,cherry,honey,hoppy,citrus,sweet
0,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,poidog,Hawaii,...,0,0,0,0,0,0,0,0,0,0
1,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,Filabee,Michigan,...,0,0,0,0,0,0,0,0,0,0
2,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,alexnblanton,Arkansas,...,0,0,0,0,0,0,0,0,0,0
3,1,Kentucky Brunch Brand Stout,4.67,4.00,4.50,5.00,4.50,4.50,beergoot,Colorado,...,0,0,0,0,0,0,0,0,0,0
4,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,dcotom,Iowa,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11959,250,Samuel Adams Utopias,4.76,4.25,5.00,4.75,4.50,4.75,Robomunky,Washington,...,0,0,0,0,0,0,0,0,0,0
11960,250,Samuel Adams Utopias,4.49,3.75,4.75,4.50,4.25,4.50,chinchill,South Carolina,...,0,1,0,0,0,0,0,0,0,0
11961,250,Samuel Adams Utopias,4.38,4.50,4.00,4.50,4.50,4.50,superspak,North Carolina,...,8,4,4,0,0,4,4,0,0,0
11962,250,Samuel Adams Utopias,4.63,4.00,4.75,4.75,4.50,4.50,skiking70,Maryland,...,0,0,0,0,0,0,0,0,0,0
11963,250,Samuel Adams Utopias,4.70,5.00,5.00,4.50,4.50,4.75,Buckeye55,North Carolina,...,0,0,0,0,0,0,0,0,0,0

In [34]:
def idf(column, attribute, map):
    texts = list(column)
    n = len(texts)
    count = 0
    for i in range(n):
        text = texts[i]
        text = str(text)
        text = text.strip()
        
        for punct in list(string.punctuation):
            text = text.replace(punct, ' ')
        text = text.lower()
        
        l_text = text.split()
        for word in l_text:
            if word in map.keys():
                text = text.replace(word, map[word])
        
        text = text.split()

        if attribute in text:
            count += 1
        
    idf = np.log10(n / count)
    return idf

dict_idf = {}
for attribute in (pbar := tqdm(attributes)):
    dict_idf[attribute] = idf(beer_reviews['comment'], attribute, beer_attribute_dict)

dict_idf

100%|██████████| 30/30 [00:06<00:00,  4.92it/s]

{'silky': 1.539997298840532,
 'crisp': 1.4191932168704706,
 'malty': 0.9297842474736399,
 'dark': 0.665358295552008,
 'coffee': 0.768223468222004,
 'tart': 1.398597809258436,
 'robust': 1.8992001598276211,
 'fruity': 0.949160011621318,
 'cinnamon': 1.3949559054687393,
 'melon': 1.436802161928665,
 'apricot': 1.558095520933328,
 'cocoa': 1.4259565601711606,
 'spicy': 1.5687863864784304,
 'vintage': 1.3380987761785652,
 'chocolaty': 0.6457006166600009,
 'papaya': 1.5374723238100283,
 'balanced': 0.7641735762207967,
 'estery': 2.140792967639735,
 'aggressive': 1.837245315754507,
 'tangerine': 1.3217083599903958,
 'roast/toast': 1.2031351461350095,
 'complex': 1.0284062280455923,
 'vanilla': 0.8114187420180788,
 'herbal': 1.5129985544268276,
 'diacetyl': 2.6950801771716963,
 'cherry': 1.5412653128271674,
 'honey': 1.61740952214931,
 'hoppy': 1.300045159143066,
 'citrus': 0.7233019634476703,
 'sweet': 0.6115476976362433}

In [35]:
for attribute in attributes:
    beer_reviews[attribute + '_tf-idf'] = (beer_reviews[attribute] * dict_idf[attribute])
beer_reviews

,pos,beer_name,final_rating,looks,smell,taste,feel,overall,user,place,...,roast/toast_tf-idf,complex_tf-idf,vanilla_tf-idf,herbal_tf-idf,diacetyl_tf-idf,cherry_tf-idf,honey_tf-idf,hoppy_tf-idf,citrus_tf-idf,sweet_tf-idf
0,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,poidog,Hawaii,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,Filabee,Michigan,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
2,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,alexnblanton,Arkansas,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
3,1,Kentucky Brunch Brand Stout,4.67,4.00,4.50,5.00,4.50,4.50,beergoot,Colorado,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
4,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,dcotom,Iowa,...,0.000000,0.000000,0.000000,0.0,0.0,1.541265,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11959,250,Samuel Adams Utopias,4.76,4.25,5.00,4.75,4.50,4.75,Robomunky,Washington,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
11960,250,Samuel Adams Utopias,4.49,3.75,4.75,4.50,4.25,4.50,chinchill,South Carolina,...,0.000000,1.028406,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
11961,250,Samuel Adams Utopias,4.38,4.50,4.00,4.50,4.50,4.50,superspak,North Carolina,...,9.625081,4.113625,3.245675,0.0,0.0,6.165061,6.469638,0.0,0.0,0.0
11962,250,Samuel Adams Utopias,4.63,4.00,4.75,4.75,4.50,4.50,skiking70,Maryland,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
11963,250,Samuel Adams Utopias,4.70,5.00,5.00,4.50,4.50,4.75,Buckeye55,North Carolina,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [36]:
attributes = input(f"Enter three attributes seperated by comma and without space from the list: {set(beer_attribute_dict.values())}")
attributes = attributes.split(',')
passer = attributes.copy()

def similarity(data, vect_2):
    vect_1 = []
    for value in data:
        vect_1.append(value)
    
    sum1 = 0
    sum2 = 0
    sum3 = 0
    for i, j in zip(vect_1, vect_2):
        sum1 = sum1 + (i * j)
        sum2 = sum2 + (i * i)
        sum3 = sum3 + (j * j)
    
    if sum1==0 or sum2==0 or sum==0:
        similarity_score = 0
    else:
        similarity_score = sum1 / (np.sqrt(sum2) * np.sqrt(sum3))
    # print(vect_1, vect_2, similarity_score)
    return similarity_score
    
vect = []
for i, attribute in enumerate(attributes):
    vect.append(dict_idf[attribute])
    attributes[i] = attribute + '_tf-idf'

beer_reviews['similarity'] = beer_reviews[attributes].apply(tuple, axis=1)
beer_reviews['similarity'] = beer_reviews['similarity'].apply(lambda row: similarity(row, vect))
disp = beer_reviews[['beer_name', 'comment', 'similarity']]
disp = disp.rename(columns={'beer_name': 'product_name', 'comment': 'product_review', 'similarity': 'similarity_score'})
disp

,product_name,product_review,similarity_score
0,Kentucky Brunch Brand Stout,"Amazing stout, expensive but worth the price!",0.000000
1,Kentucky Brunch Brand Stout,This beer meet and exceeded all the unreal hyp...,0.000000
2,Kentucky Brunch Brand Stout,Let it sit and warm to the room a little ... u...,0.000000
3,Kentucky Brunch Brand Stout,"A small pour, ebony dark, no real head. Intens...",0.384317
4,Kentucky Brunch Brand Stout,"Vintage 2022, served on tap at Toppling Goliat...",0.537051
...,...,...,...
11959,Samuel Adams Utopias,It seems weird to rate this like it's a normal...,0.000000
11960,Samuel Adams Utopias,"Shared 2017 canister. Fabulous, very complex a...",0.000000
11961,Samuel Adams Utopias,8000th review! 8 ounce pour from a 24 ounce bo...,0.539937
11962,Samuel Adams Utopias,Such a huge beer and a joy to drink. This is d...,0.000000
11963,Samuel Adams Utopias,The odd beer that smells better than it tastes...,0.384317

### Task D

In [37]:
re_calculate = False
if re_calculate == True:
    def sentiment_openai(data):
        openai_key = input("Provide API Key:")
        i = 0
        for iter in tqdm(data):
            sents = []
            final_rating, text = iter
            openai.api_key = openai_key
            prompt = f'''Provide a sentiment score for "{text}" in a range of +5 to -5. This comment was overall rated as {final_rating} by the user on a scale of 0-5. Watchout for the light human sarcasm in the quoted text. Only provide the number.'''

            try:
                # @backoff.on_exception(backoff.expo, (ServiceUnavailableError, APIError))
                def chat_completion(prompt):
                    response = openai.ChatCompletion.create(
                    model="gpt-3.5-turbo",
                    messages=[
                            {"role": "system", "content": prompt},
                        ]
                    )

                    score = response['choices'][0]['message']['content']
                    return score
                
                score = chat_completion(prompt)
            except (ServiceUnavailableError, APIError, Timeout) as error:
                score = -1
            sents.append([text, score])
            
            sents = pd.DataFrame(sents, columns=['comment', 'sentiment'])
            
            if i==0:
                sents.to_csv(path + '/Support Files/sentiments.csv', mode='a', index=False, header=True)
            else:
                sents.to_csv(path + '/Support Files/sentiments.csv', mode='a', index=False, header=False)
            
            i += 1
            # time.sleep(1)
        
    beer_reviews['sentiment'] = beer_reviews[['final_rating', 'comment']].apply(tuple, axis=1)
    sentiment_openai(beer_reviews['sentiment'])
    beer_reviews = beer_reviews.drop(['sentiment'], axis=1)

    sentiment = pd.read_csv(path + '/Support Files/sentiments.csv')
    sentiment = sentiment.astype({'sentiment':float})
    sentiment = sentiment.drop_duplicates('comment', keep='last')
    beer_reviews = beer_reviews.merge(sentiment, left_on='comment', right_on='comment', how='left')
else:
    sentiment = pd.read_csv(path + '/Support Files/sentiments.csv')
    sentiment = sentiment.astype({'sentiment':float})
    sentiment = sentiment.drop_duplicates('comment', keep='last')
    beer_reviews = beer_reviews.merge(sentiment, left_on='comment', right_on='comment', how='left')

beer_reviews['sentiment'] = beer_reviews['sentiment'].replace(0, 0.0000001)
display(beer_reviews)
display(beer_reviews[['beer_name','comment','sentiment']])

,pos,beer_name,final_rating,looks,smell,taste,feel,overall,user,place,...,vanilla_tf-idf,herbal_tf-idf,diacetyl_tf-idf,cherry_tf-idf,honey_tf-idf,hoppy_tf-idf,citrus_tf-idf,sweet_tf-idf,similarity,sentiment
0,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,poidog,Hawaii,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,4.00
1,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,Filabee,Michigan,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,4.00
2,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,alexnblanton,Arkansas,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,-3.00
3,1,Kentucky Brunch Brand Stout,4.67,4.00,4.50,5.00,4.50,4.50,beergoot,Colorado,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.384317,3.50
4,1,Kentucky Brunch Brand Stout,5.00,5.00,5.00,5.00,5.00,5.00,dcotom,Iowa,...,0.000000,0.0,0.0,1.541265,0.000000,0.0,0.0,0.0,0.537051,4.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11888,250,Samuel Adams Utopias,4.76,4.25,5.00,4.75,4.50,4.75,Robomunky,Washington,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,4.76
11889,250,Samuel Adams Utopias,4.49,3.75,4.75,4.50,4.25,4.50,chinchill,South Carolina,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,4.49
11890,250,Samuel Adams Utopias,4.38,4.50,4.00,4.50,4.50,4.50,superspak,North Carolina,...,3.245675,0.0,0.0,6.165061,6.469638,0.0,0.0,0.0,0.539937,3.89
11891,250,Samuel Adams Utopias,4.63,4.00,4.75,4.75,4.50,4.50,skiking70,Maryland,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,4.63
11892,250,Samuel Adams Utopias,4.70,5.00,5.00,4.50,4.50,4.75,Buckeye55,North Carolina,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.384317,3.80

,beer_name,comment,sentiment
0,Kentucky Brunch Brand Stout,"Amazing stout, expensive but worth the price!",4.00
1,Kentucky Brunch Brand Stout,This beer meet and exceeded all the unreal hyp...,4.00
2,Kentucky Brunch Brand Stout,Let it sit and warm to the room a little ... u...,-3.00
3,Kentucky Brunch Brand Stout,"A small pour, ebony dark, no real head. Intens...",3.50
4,Kentucky Brunch Brand Stout,"Vintage 2022, served on tap at Toppling Goliat...",4.80
...,...,...,...
11888,Samuel Adams Utopias,It seems weird to rate this like it's a normal...,4.76
11889,Samuel Adams Utopias,"Shared 2017 canister. Fabulous, very complex a...",4.49
11890,Samuel Adams Utopias,8000th review! 8 ounce pour from a 24 ounce bo...,3.89
11891,Samuel Adams Utopias,Such a huge beer and a joy to drink. This is d...,4.63
11892,Samuel Adams Utopias,The odd beer that smells better than it tastes...,3.80

### Task E

In [38]:
max_sty = max(beer_reviews['similarity'])
min_sty = min(beer_reviews['similarity'])
df_bow = beer_reviews
recommended = beer_reviews.loc[(beer_reviews['sentiment'] > 0)].copy()
recommended['similarity_non_scaled'] = recommended['similarity']
recommended = recommended.loc[recommended['similarity_non_scaled'] > 0]
recommended['similarity'] = 5 * ((recommended['similarity'] - min_sty) / (max_sty - min_sty))
recommended['similarity'] = np.log(recommended['similarity']) / np.log(2.5)

## WHY LOG?  Is it to make it positive? negative sentiment hai k nahi?
#2.5 se jyada hogya toh overall mai jyada significnce dega...toh basically sentiment (2) se jyada weight hoga
# recommended = recommended.loc[recommended['similarity'] > 1]
recommended['sentiment'] = np.log(recommended['sentiment']) / np.log(2)
recommended = recommended.loc[(recommended['sentiment'] > 0)]
recommended['final_score'] = recommended['sentiment'] * recommended['sentiment']
# recommended

In [39]:
recommended = recommended.loc[recommended['final_score'] > 1]
recommended = recommended.groupby('beer_name').agg(
                    sentiment = pd.NamedAgg('sentiment', aggfunc='mean'),
                    similarity = pd.NamedAgg('similarity', aggfunc='mean'),
                    avg_final_score = pd.NamedAgg('final_score', aggfunc='mean'),
                    count_reviews = pd.NamedAgg('beer_name', aggfunc='count')
                    )
recommended = recommended.reset_index(drop=False)
recommended['scaled_score'] = np.log10(recommended['count_reviews']) * np.log2(recommended['avg_final_score'])
bow_unsorted = recommended.copy()
recommended = recommended.sort_values('scaled_score', ascending=False)
recommended_bow = recommended[:3].drop(['sentiment', 'similarity'], axis=1)
print(f'Selected attributes: {passer}')
print('Three recommended beers: using bag-of-words')
display(recommended_bow)

Selected attributes: ['hoppy', 'malty', 'dark']
Three recommended beers: using bag-of-words

,beer_name,avg_final_score,count_reviews,scaled_score
130,KBS - Maple Mackinac Fudge,4.364910,141,4.569136
45,CBS (Canadian Breakfast Stout),4.410659,124,4.482003
41,Bourbon County Brand Stout,4.385349,112,4.370350

### Part F

In [40]:
attributes = passer

re_calculate = False
if re_calculate:
    def spacySimilarity(comments, attributes, map):
        nlp = spacy.load("en_core_web_md")

        comments = list(comments)
        attributes = list(attributes)
        similarity_scores = []
        for comment in tqdm(comments):
            row = []
            row.append(comment)
            for attribute in attributes:
                text1 = attribute
                text2 = comment

                text2 = text2.strip()
                for punct in list(string.punctuation):
                    text2 = text2.replace(punct, ' ')
                text2 = text2.lower()

                l_text = text2.split()
                for word in l_text:
                    if word in map.keys():
                        text2 = text2.replace(word, map[word])

                text2 = ''.join(text2)

                doc1 = nlp(text1)
                doc2 = nlp(text2)
                similarity = doc1.similarity(doc2)
                row.append(similarity)
            similarity_scores.append(row)
        
        new_attributtes = ['comment']
        for i in range(len(attributes)):
            new_attributtes.append(attributes[i] + "_SSimilarity")
        
        similarity = pd.DataFrame(similarity_scores, columns=new_attributtes)
        similarity.to_csv(path + '/Support Files/similarity_spacy.csv', index=False)

    spacySimilarity(beer_reviews['comment'], set(beer_attribute_dict.values()), beer_attribute_dict)
    
    new_attributtes = ['comment']
    for i in range(len(attributes)):
        new_attributtes.append(attributes[i] + "_SSimilarity")
    
    similarity = pd.read_csv(path + '/Support Files/similarity_spacy.csv').drop_duplicates()
    similarity = similarity[new_attributtes]
    beer_reviews = beer_reviews.merge(similarity, left_on='comment', right_on='comment', how='left')
    display(beer_reviews)
else:
    new_attributtes = ['comment']
    for i in range(len(attributes)):
        new_attributtes.append(attributes[i] + "_SSimilarity")
    
    similarity = pd.read_csv(path + '/Support Files/similarity_spacy.csv').drop_duplicates()
    similarity = similarity[new_attributtes]
    beer_reviews = beer_reviews.merge(similarity, left_on='comment', right_on='comment', how='left')
    # display(beer_reviews)

In [41]:
new_attributtes = new_attributtes[1:]
beer_reviews['Ssimilarity'] = 1
for attri in new_attributtes:
    beer_reviews['Ssimilarity'] = beer_reviews['Ssimilarity'] * beer_reviews[attri]

max_sty = max(beer_reviews['Ssimilarity'])
min_sty = min(beer_reviews['Ssimilarity'])
df_wv = beer_reviews
recommended = beer_reviews.loc[(beer_reviews['sentiment'] > 0)].copy()
recommended['Ssimilarity_non_scaled'] = recommended['Ssimilarity']
recommended = recommended.loc[recommended['Ssimilarity_non_scaled'] > 0]
recommended['Ssimilarity'] = 5 * ((recommended['Ssimilarity'] - min_sty) / (max_sty - min_sty))
recommended['Ssimilarity'] = np.log(recommended['Ssimilarity']) / np.log(2.5)
# recommended = recommended.loc[recommended['Ssimilarity'] > 1]
recommended['sentiment'] = np.log(recommended['sentiment']) / np.log(2)
recommended = recommended.loc[(recommended['sentiment'] > 0)]
recommended['Sffinal_score'] = recommended['Ssimilarity'] * recommended['sentiment']
# recommended

In [42]:
recommended = recommended.loc[recommended['Sffinal_score'] > 1]
recommended = recommended.groupby('beer_name').agg(
                    sentiment = pd.NamedAgg('sentiment', aggfunc='mean'),
                    similarity = pd.NamedAgg('Ssimilarity', aggfunc='mean'),
                    avg_final_score = pd.NamedAgg('Sffinal_score', aggfunc='mean'),
                    count_reviews = pd.NamedAgg('beer_name', aggfunc='count')
                    )
recommended  = recommended.reset_index(drop=False)
recommended['scaled_score'] = np.log10(recommended['count_reviews']) * (np.log2(recommended['avg_final_score']) / np.log2(1.5))
spacy_unsorted = recommended.copy()
recommended = recommended.sort_values('scaled_score', ascending=False)
recommended_spacy = recommended[:3].drop(['sentiment', 'similarity'], axis=1)
print(f'Selected attributes: {passer}')
print('Three recommended beers:using word-embeddings')
display(recommended_spacy)

Selected attributes: ['hoppy', 'malty', 'dark']
Three recommended beers:using word-embeddings

,beer_name,avg_final_score,count_reviews,scaled_score
121,KBS - Maple Mackinac Fudge,1.698513,49,2.208296
120,KBS,1.721900,32,2.017291
42,CBS (Canadian Breakfast Stout),1.655360,38,1.963771

In [43]:
beers = list(recommended_bow['beer_name'])
cols = ['beer_name']
for item in passer:
    cols.append(item)

perc_data = []
for beer in beers:
    row = []
    row.append(beer)
    df = df_bow.loc[df_bow['beer_name'] == beer][cols]
    for item in passer:
        perc = round((len(df.loc[df[item] > 0]) / len(df)) * 100, 2)
        row.append(perc)
    perc_data.append(row)

for i in range(len(cols)):
    if i!=0:
        cols[i] = "% mentions of " + cols[i]

perc_data = pd.DataFrame(perc_data, columns=cols)
print("% Mentions using BOW:")
display(perc_data)


beers = list(recommended_spacy['beer_name'])
cols = ['beer_name']
for item in passer:
    cols.append(item)

perc_data = []
for beer in beers:
    row = []
    row.append(beer)
    df = df_bow.loc[df_wv['beer_name'] == beer][cols]
    for item in passer:
        perc = round((len(df.loc[df[item] > 0]) / len(df)) * 100, 2)
        row.append(perc)
    perc_data.append(row)

for i in range(len(cols)):
    if i!=0:
        cols[i] = "% mentions of " + cols[i]

perc_data = pd.DataFrame(perc_data, columns=cols)
print("% Mentions using Word Embeddings:")
display(perc_data)

% Mentions using BOW:

,beer_name,% mentions of hoppy,% mentions of malty,% mentions of dark
0,KBS - Maple Mackinac Fudge,0.31,11.15,43.34
1,CBS (Canadian Breakfast Stout),0.65,10.10,37.46
2,Bourbon County Brand Stout,0.00,8.05,47.46

% Mentions using Word Embeddings:

,beer_name,% mentions of hoppy,% mentions of malty,% mentions of dark
0,KBS - Maple Mackinac Fudge,0.31,11.15,43.34
1,KBS,0.00,12.06,39.36
2,CBS (Canadian Breakfast Stout),0.65,10.10,37.46

**How would your recommendation change if you use word vectors (e.g., the spaCy package with medium-sized pretrained word vectors) instead of the plain vanilla bag-of-words cosine similarity?**

**Analysis of Recommendation Impact:**

We examined the percentage of mentions for the 'beer_name' as shown in the table above. Our observations revealed the following:

1. **Bag-of-Words (BOW) vs. Word Embeddings:**

   - With the Bag-of-Words (BOW) approach, the percentage of mentions is significantly higher than with word embeddings, particularly for the 'Hoppy' attribute.
   
   - However, it's important to note that the percentage of mentions for the 'dark' attribute is higher with word embeddings.

2. **Choosing the Right Approach:**

   - Determining which approach is better is challenging. However, it is more crucial to select the one that aligns with the actual business objective.

   - Additionally, considering the importance of each attribute among these three can aid in making an informed decision.

**In Summary:**

The choice between bag-of-words (BOW) and word embeddings like spaCy's pretrained word vectors depends on the desired outcome and the nature of the data. BOW may provide higher percentages for some attributes, while word embeddings can capture more nuanced relationships, as seen with the 'dark' attribute. Careful consideration of the business objective and attribute importance is key to making an informed decision between these two approaches.

### TASK G

Using BOW

In [44]:
rec = bow_unsorted
print('Socres of top beers:')
display(rec.loc[(rec['beer_name'] == 'Kentucky Brunch Brand Stout') | (rec['beer_name'] == 'Vanilla Bean Assassin') | (rec['beer_name'] == 'Marshmallow Handjee')])

print('Socres of recommended beers:')
recommended = list(recommended_bow['beer_name'])
display(rec.loc[(rec['beer_name'] == recommended[0]) | (rec['beer_name'] == recommended[1]) | (rec['beer_name'] == recommended[2])])

Socres of top beers:

,beer_name,sentiment,similarity,avg_final_score,count_reviews,scaled_score
133,Kentucky Brunch Brand Stout,2.106518,0.801465,4.508504,16,2.616130
146,Marshmallow Handjee,1.971597,0.785858,3.971442,10,1.989663
217,Vanilla Bean Assassin,2.198102,0.712819,4.847758,5,1.591777

Socres of recommended beers:

,beer_name,sentiment,similarity,avg_final_score,count_reviews,scaled_score
41,Bourbon County Brand Stout,2.080402,0.789709,4.385349,112,4.370350
45,CBS (Canadian Breakfast Stout),2.090066,0.839186,4.410659,124,4.482003
130,KBS - Maple Mackinac Fudge,2.075194,0.837291,4.364910,141,4.569136

Using Spcacy

In [45]:
rec = spacy_unsorted
print('Socres of top beers:')
display(rec.loc[(rec['beer_name'] == 'Kentucky Brunch Brand Stout') | (rec['beer_name'] == 'Vanilla Bean Assassin') | (rec['beer_name'] == 'Marshmallow Handjee')])

print('Socres of recommended beers:')
recommended = list(recommended_spacy['beer_name'])
display(rec.loc[(rec['beer_name'] == recommended[0]) | (rec['beer_name'] == recommended[1]) | (rec['beer_name'] == recommended[2])])

Socres of top beers:

,beer_name,sentiment,similarity,avg_final_score,count_reviews,scaled_score
123,Kentucky Brunch Brand Stout,2.121917,0.829018,1.769571,9,1.343202
136,Marshmallow Handjee,1.998796,0.780763,1.523648,3,0.495528
206,Vanilla Bean Assassin,2.254667,0.764754,1.729911,3,0.644928

Socres of recommended beers:

,beer_name,sentiment,similarity,avg_final_score,count_reviews,scaled_score
42,CBS (Canadian Breakfast Stout),2.169240,0.762657,1.655360,38,1.963771
120,KBS,2.156554,0.793501,1.721900,32,2.017291
121,KBS - Maple Mackinac Fudge,2.109931,0.804455,1.698513,49,2.208296

**Do you see any difference across bag-of-words and word vector approaches? Explain.**

We can see three things above:

A. Score of the top 3 beers in the entire dataset using Bag-of-Words and Word Vector.

B. Top 3 Recommended beers using Bag-of-Words.

C. Top 3 Recommended beers using Word Vector.

**Analysis of the Differences:**

1. **Review Count Impact**: We observe that the top 3 beers from the entire dataset using both Bag-of-Words and Word Vector have very low review counts. Consequently, the overall rating may rely heavily on these few reviews, making it less reliable as a recommendation.

2. **Scaled Scores**: The scaled scores for these beers are comparatively lower than the recommended beers obtained via Bag-of-Words and Word Vector.

3. **Personalized Recommendations**: The recommended beers are selected based on specific user preferences and reviews, making them potentially more aligned with the user's tastes. The inclusion of similarity and sentiment scores allows for a more personalized and context-aware recommendation that considers user-specific criteria.

**In Summary:**

Choosing the top 3 highest-rated products from the entire dataset may meet the user's requirements if they prioritize overall ratings above all else. However, this approach neglects the personalized aspect of recommendations and may not account for specific user preferences or sentiments. Recommendations based on similarity and sentiment scores provide a more tailored and context-aware approach, which can be more useful for users seeking products that align with their individual tastes and preferences.

### Task H

In [46]:
def lift(texts, x, y, words=float('inf')):
    x = x.replace(' ', '')
    y = y.replace(' ', '')

    n = len(texts)
    count_x = 0
    count_y = 0
    count_x_y = 0

    for i in range(n):
        x_indices = []
        y_indices = []
        text = texts[i].split()
        
        for j in range(len(text)):
            if x == text[j]:
                x_indices.append(j)
            elif y == text[j]:
                y_indices.append(j)

        n_words = []    
        for x_index in x_indices:
            for y_index in y_indices:
                n_words.append(abs(x_index - y_index) - 1)
        
        # print(len(n_words) > 0, len(x_indices) > 0, len(y_indices) > 0)
        if len(n_words) > 0:
            if float(min(n_words)) <= float(words):
                count_x_y += 1
        if len(x_indices) > 0:
            count_x += 1
        if len(y_indices) > 0:
            count_y += 1
        
    # print(n, x, y, count_x_y, count_x, count_y)
    
    try:
        lift = (n * count_x_y) / (count_x * count_y)
    except ZeroDivisionError:
        lift = np.nan
    return lift

In [47]:
comments = process_column(beer_reviews['comment'])
beer_name = list(beer_reviews['beer_name'])
for i in range(len(beer_name)):
    beer_name[i] = beer_name[i].replace(' ', '')

comments = replace_car_brands(comments, beer_attribute_dict)
for i in range(len(comments)):
    comments[i] = ' '.join(comments[i])
    comments[i] = beer_name[i] + ' - ' + comments[i]
    comments[i] = comments[i].strip()

beers = list(beer_reviews['beer_name'].value_counts()[:10].index)
attributes = ['hoppy', 'malty', 'dark', 'complex']

lifts = []
for beer in beers:
    row = []
    row.append(beer)
    for attribute in attributes:
        lift_score = lift(comments, beer, attribute)
        row.append(lift_score)
    lifts.append(row)

cols = ['beer_name']
for attribute in attributes:
    cols.append(attribute)

lifts = pd.DataFrame(lifts, columns=cols)
lifts = lifts.set_index('beer_name')
lifts

                                   hoppy     malty      dark   complex
beer_name
King Sue                        1.700400  0.980775  0.081186  0.642162
Heady Topper                    3.274300  0.895490  0.186251  0.760206
KBS - Maple Mackinac Fudge      0.061779  0.948166  2.005782  0.627997
CBS (Canadian Breakfast Stout)  0.129998  0.859028  1.733476  1.286677
KBS                             0.000000  1.025685  1.821513  1.362886
Zombie Dust                     3.534411  2.071853  0.204913  0.630314
Pseudo Sue                      2.504119  1.367817  0.072590  0.502397
Pliny The Elder                 3.146384  1.447275  0.115211  0.398687
Bourbon County Brand Stout      0.000000  0.684898  2.196162  1.899956
Focal Banger                    2.494337  1.772324  0.000000  0.642534

In [48]:
similar_beers = []
liked_beer = 'King Sue'
for beer in list(lifts.index):
    v1 = np.array(lifts.loc[liked_beer].values)
    v1 = v1.reshape(1, -1)
    if beer != liked_beer:
        v2 = np.array(lifts.loc[beer].values)
        v2 = v2.reshape(1, -1)
        cosines_sim = cosine_similarity(v1, v2)[0][0]
        similar_beers.append([beer, cosines_sim])

similar_beers = pd.DataFrame(similar_beers,columns=['beer_name', 'cosine_similarity'])
similar_beers = similar_beers.sort_values('cosine_similarity', ascending=False)
similar_beers

                        beer_name  cosine_similarity
5                      Pseudo Sue           0.989610
8                    Focal Banger           0.989124
4                     Zombie Dust           0.986614
6                 Pliny The Elder           0.975772
0                    Heady Topper           0.965110
2  CBS (Canadian Breakfast Stout)           0.422158
3                             KBS           0.393378
1      KBS - Maple Mackinac Fudge           0.335831
7      Bourbon County Brand Stout           0.335676

**Choose one beer and find the most similar beer (among the remaining 9) using the lift values. Explain your method.**

1. **Lift Calculation:**

Initially, we calculated the lift values between the chosen attributes: 'hoppy,' 'malty,' 'dark,' and 'complex' for any 10 beers in the dataset.

2. **Selection of Reference Beer:**

Among the available options, 'King Sue' was chosen as one of the reference beers.

3. **Cosine Similarity Analysis:**

To find the most similar beers to 'King Sue,' we employed the cosine similarity metric. This metric allows us to measure the similarity in attribute preferences between 'King Sue' and other beers.

4. **Table Sorting:**

The table displayed above is sorted based on the cosine similarity values. This sorting arrangement helps identify the most similar beers to 'King Sue' among the remaining 9 beers.